### ISSUE TITLE
Emoji invalid XML?

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphonycms#2315]
From the [forum](http://www.getsymphony.com/discuss/thread/109445/)...

> When I try manually saving an entry with an emoji character in a text field, I get an error like
> 
> > ‘Body’ contains invalid XML. The following error was returned: loadXML(): Char 0xD83D out of allowed range in Entity, line: 1

**Comment by nitriques** [comment]
Looks like libxml does not like emojis...

Using <![CDATA[&#xd83d]]> might be the only solution...

**Comment by jensscherbl** [comment]
I think we should leave this open and adress it along with #2292 for 3.0.0.

**Comment by nitriques** [comment]
Absolutely. There are some php libs to parse emojis..

**Comment by brendo** [comment]
Named entities generally don't work with XML, decimal entities do though so `&#55357;` will work (though I'm not sure how many browsers will support that?)

**Comment by michael-e** [comment]
As a sidenote: 4-byte characters can not be saved in MySQL databases easily.

> The character set named utf8 uses a maximum of three bytes per character and contains only BMP characters. As of MySQL 5.5.3, the utf8mb4 character set uses a maximum of four bytes per character supports supplemental characters  
– https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html

**Comment by nitriques** [comment]
> As a sidenote: 4-byte characters can not be saved in MySQL databases easily.

That's interesting @michael-e thanks for sharing.

**Comment by michael-e** [comment]
We should make Symphony work with 4-byte-characters out of the box.

I had a discussion with @nilshoerrmann today, and I think we shouldn't only do it for Symphony 3, but also for the 2.x branch. The latter would probably mean to release "2.7", because we must raise the MySQL requirement to 5.5.3, AFAIK.

The main issue here is changing all database columns to use `utf8mb4` instead of `utf8`. Implementing the necessary table updates for the MySQL database is not trivial, because we must think about the length of columns and indexes.

Mathias Bynens wrote a great article about this: <https://mathiasbynens.be/notes/mysql-utf8mb4>

What do you think, @brendo, @jensscherbl ?

**Comment by nilshoerrmann** [comment]
> I think we shouldn't only do it for Symphony 3, but also for the 2.x branch.

One of our sites uses a combination of Remote Data Sources and XML Importers (using the Data Source based `integration` branch) to fetch and store Facebook and Twitter posts. This site broke completely because of the usage of emojis, displaying a Symphony database error to the user. 

So I think this issue should be considered as a bug report and not a feature request which justifies a point release. Although the real bug is a poor unicode implementation in MySQL, it's Symphony that fails while saving entries.

**Comment by jonmifsud** [comment]
Conform with Nils, just had a client whose site basically crashed when
saving an entry with an embedded tweet containing an emoji. Error wasn't
just in the backend but went straight to frontend.

**Comment by jensscherbl** [comment]
> The latter would probably mean to release "2.7", because we must raise the MySQL requirement to 5.5.3, AFAIK.

> What do you think, @brendo, @jensscherbl ?

I think raising the MySQL requirement is a breaking change. Breaking changes [require a new major version][1] (3.0.0).

[1]: http://semver.org

**Comment by michael-e** [comment]
Good point. Unfortunately this means that we can't bring a fix to the current stable version of Symphony, unless we push everything _one version up_:

* Symphony 2.6 gets a "utf8mb4 upgrade" and is released as "Symphony 3"
* The codebase that is currently called "Symphony 3" will be "Symphony 4"

**Comment by jensscherbl** [comment]
> Unfortunately this means that we can't bring a fix to the current stable version of Symphony, unless we push everything one version up

Yep. Was also the case with #2106, for example. Question is, why is this so important compared to other issues that it can't wait for the 3.0.0 release? Does it really justify an in-between major release just for that? Could it be provided as an extension or an optional, standalone update script instead until 3.0.0 is released?

**Comment by michael-e** [comment]
Still thinking about it…

**Comment by jonmifsud** [comment]
Michael I think at least catching the 4 byte character - and showing a
usual invalid error rather than saving incomplete data the could be
sufficient in most cases for 2.6.x - if symphony 3 will support these
characters then this 'error' message would be removed.

**Comment by michael-e** [comment]
Yes, we might do that—just prevent breaking the output. But let's wait a bit, I developed a "hackish" solution for Nils which I would like to discuss and test with him first.

But: Apparently the `utfmb4` character set was introduced in MySQL 5.5, so we **wouldn't need to raise the requirement** in order to provide a proper fix. (The version number 5.5.3 was a mis-interpretation on my side.)

I am still trying to wrap my head around the necessitiy to change column lengths when using `utf8mb4`. Sure, maximum index lengths are lower then (the precise value depends on the storage engine), but still I don't understand why Mathias Bynens suggests limiting the column length. It is possible to use a "prefix" index, which is shorter than your column.

As always, when opening Pandora's box, interesting questions are raised. Why do we limit `VARCHAR` columns (which are used for Input Fields) to 255 bytes? Probably for historical reasons, because this limit has been improved to 65,535 bytes in MySQL 5.0.3, a long time ago.

**Comment by michael-e** [comment]
Unfortunately, Mathias Bynen was right regarding the requirement (MySQL 5.5.3). It' teriibly hard to find this in the MySQL docs, but finally I found it. `utf8mb4` was introduced in MySQL 5.5.3.

**Comment by michael-e** [comment]
BTW, I figured out how an database (table) update would basically work. But given the [requirement issue](https://github.com/symphonycms/symphony-2/issues/2315#issuecomment-110801239), I still have to think about how to proceed from here, conceptually.

**Comment by nilshoerrmann** [comment]
From what you've explained to me on the phone, @michael-e, I'd be happy if Symphony offered a way to set the default charset used to communicate with the database. A setting in the config file or something alike.

This would offer me a way to manually change the specific tables that need to store emojis without requiring an update to Symphony 3.0.0. The latter will most likely not be suitable for my project due to extension incompatibilities.

> But given the requirement issue, I still have to think about how to proceed from here, conceptually. 

As I already said on the phone, I'm not sure if we need to work on an automatic updater: If there was a way in Symphony 2 to work around this issue manually, Symphony 3 could introduce a new MySQL requirement without thinking about backwards compatibility or older table settings and indexes.

**Comment by michael-e** [comment]
> I'm not sure if we need to work on an automatic updater

So am I. But advising people to manually fiddle in the database has its risks. :-)

**Comment by nilshoerrmann** [comment]
Life is always risky ;)

**Comment by nitriques** [comment]
I very like the idea of having a default charset in the config file. But would you allow custom sql statement  with other charset or take the same approach to when we tried to fix the collate sql  (i.e. `preg_replace` ?)

> I'm not sure if we need to work on an automatic updater

I would rather see an extension doing it.

**Comment by nilshoerrmann** [comment]
> But would you allow custom sql statement with other charset …

With the emoji problem as background it makes a lot of sense to allow custom settings for queries.

**Comment by michael-e** [comment]
@nitriques:

> But would you allow custom sql statement with other charset or take the same approach to when we tried to fix the collate sql (i.e. preg_replace ?)

I don't remember, what exactly do you mean?

A simple solution, as proposed by @nilshoerrmann, would be:

* We add a (secret) configuration setting for the connection character set (e.g. `connection_utfbmb4` in the `database` section of the config file). In my eyes this is completely backwards compatible, because it essentially means "expect up to 4 bytes per character" (instead of "expect up to 3 bytes"). So the connection setting alone does not require any changes to the database.
* Changing existing colums/tables from `utf8` to `utf8mb4` is up to the developer. (We might provide some instructions, maybe.)
* Same applies to newly created tables.

Sounds simple, but there is one hickup: We may have to change the code/logic of some Symphony fields anyway. :-(

* If we want to prevent the output from breaking (which is the original issue), fields **must filter** 4-byte-characters.
* If we want to actually use `utf8mb4` on certain columns, we want to **pass** 4-byte-characters.

Remember that the same field (e.g. _Input Field_) might have some use cases with `utf8`and some with `utf8mb4` in the same system.

This is gonna be chaotic. (And even if we make it work, we might have some support work because people broke their databases.)

The second solution is a complete updater. It raises its own questions:

* Do we really want to release an "in-between 3.0" version of Symphony (see above, we would raise the MySQL requirement…)
* Is it wise to change all tables in the database? (Wordpress, for example, has only changed some tables.) Needs some research.
* If not, which fields should allow 4-byte-characters? Needs some research/discussion.

I would like to wait for @brendo at this point.

**Comment by nilshoerrmann** [comment]
> We add a (secret) configuration setting for the connection character set (e.g. connection_utfbmb4 in the database section of the config file).

I thought of something simple like a `charset` setting ind the `database` section which defaults ot `utf8` and could be used here instead of the hardcoded default value:

- https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.mysql.php#L391
- https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.mysql.php#L405

If I understood you correctly, @michael-e, this would allow me to switch to the needed charset in my install.

**Comment by michael-e** [comment]
Yes, it would, but my main concern is the "hickup" I described above:

> * If we want to prevent the output from breaking (which is the original issue), fields **must filter** 4-byte-characters.
> * If we want to actually use `utf8mb4` on certain columns, we want to **pass** 4-byte-characters.

How can we solve this? Or shall we say we don't care?

**Comment by nilshoerrmann** [comment]
This is really not my area of expertise but couldn't Symphony's database class decide based on the charset setting? 

- If the charset is `utf8`, filter out 4-byte-characters.
- If the charset is `uft8mb4`, do nothing.

**Comment by michael-e** [comment]
Maybe, I would have to check. But if we rely solely on the character set of the **connection**, you may still have "mixed database content", so things may still break. At this point we don't know about your DB columns.

**Comment by jensscherbl** [comment]
> Remember that the same field (e.g. Input Field) might have some use cases with utf8and some with utf8mb4 in the same system.

> If not, which fields should allow 4-byte-characters? Needs some research/discussion.

Not completely sure about this, but my understanding after reading the Mathias Bynen article was that `utf8mb4` is actually the right UTF-8, and that `utf8mb4` exists in MySQL because MySQL's default `utf8` is kind of a stripped down version of UTF-8.

So in my opinion, fields don't have to filter anything or need to be changed to support 4-byte-characters. If a field already supports UTF-8, it should be good to go.

**Comment by michael-e** [comment]
> `utf8mb4` is actually the right UTF-8

Yep. correct.

> If a field already supports UTF-8, it should be good to go.

Yes and no, **If we update the existing database** (i.e. all tables of this field), we only have to **change the table creation of the field** (for future tables).

**Comment by jensscherbl** [comment]
>  If we update the existing database (i.e. all tables of this field), we only have to change the table creation of the field (for future tables).

Wasn't this the plan?

**Comment by michael-e** [comment]
But this means that fields are not "good to go". Every (core/extension) field has to be changed to create new tables with the new character set (and collation).

**Comment by jensscherbl** [comment]
Get it now. Sorry for the confusion.

**Comment by nitriques** [comment]
@michael-e Sorry for the delay, but I was thinking about [this line](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.mysql.php#L538) in particular, where we force feed the change (which prevents me from writing my custom SQL).

Also:

>  If we update the existing database (i.e. all tables of this field), we only have to change the table creation of the field (for future tables).

I would rather no mix collations into the same DB. I would only activate utf8m4 for new installs and let developers do what they want with the old ones.

> Every (core/extension) field has to be changed to create new tables with the new character set (and collation).

If they did not specify anything in their SQL, it will use the default one right ?

**Comment by michael-e** [comment]
The line you mention is simply replacing `TYPE=` by `ENGINE=`, which is more "modern" MySQL speak. It doesn't force a DB engine though, nor any character set or collation.

The needle eye for Emojis is the default values in [these two functions](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.mysql.php#L391-L409) – those functions set the connection character set. They are not called with a parameter value by Symphony, so the defaults will be used. If you change these two defaults to `uft8mb4`, you can use the same character set in your tables as well.

> I would rather no mix collations into the same DB. I would only activate utf8m4 for new installs and let developers do what they want with the old ones.

Well, in my tests I did not notice any problems.

If we look for a simple solution for Symphony 2.x, we might follow @nilshoerrmann's idea:

* Add a (secret) config setting that sets the default for the functions mentioned above. A developer may set the value to `utf8mb4`, then experiment with his database tables **at his own risk**.

> If they did not specify anything in their SQL, it will use the default one right ?

Yes, but people never get the default database setting right, especially not on shared hosting (where they actually have no influence). This is why we explicitely added the DB table's character set and collation to all fields.

**Comment by nitriques** [comment]
Ok wow great recap. Thanks.

**Comment by jonmifsud** [comment]
I know this has been a while but I've been playing with it due to a client request. These are some of the things I came across:

1. handles still seem to include utf8mb4 characters - I think these should be stripped out.
2. changing charset to utf8mb4 on varchars means we have to reduce the characters allowed from 255 as if they have an index, the maximum size of an indexed field is 1000bytes (at least on my database) This causes issues in case of handle functions where the string is full, meaning we'd have them cropped. Or otherwise drop the index. Shouldn't be an issue for new installs.
3.Forcing the symphony charset to utf8mb4 seems reasonable given that it acts just fine with utf8 encoded tables when the data is only in standard utf8, only issue is when sending utf8mb4 characters ot utf8 encoded fields, which throws a 500 server error. The same thing happens if we leave the charset to utf8.

I think changing the charset with a "warning message" that utf8 encoded tables will still have problems with utf8mb4 characters might suffice. In terms of error catching though, we can be a bit smart and at least for 2.x when there is a database exception, we test for the exception containing utf8mb4 data, and in which case we say - emoticons are not supported on your setup - and provide a link to obtain more information.

**Comment by jonmifsud** [comment]
@nitriques when you have a few spare minutes could you have a look at my last comment?

**Comment by nitriques** [comment]
@jonmifsud I really do not know what to do anymore. There are drawbacks to every solution.

I think that the safest route is to allow this to be configured by the developer. I am not sure about a warning to the end user...

I'll have to think a lot more on the issue to plan something, but, as always, any feedback is appreciated.

**Comment by nitriques** [comment]
Fixed as per #2369 (in the comments!)

**Comment by Lvalueshiny393** [comment]
@nitriques https://lnkr.fun/2004ee3

**Comment by brendo** [comment]
So nice to see you all again but I'm going to go out on limb and say, don't click that link 😆
